<?php

use yii\db\Migration;
use yii\db\Schema;

class m200001_000006_setting_marketplace_kategori extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('setting_marketplace_kategori', [
            'kode_toko' => $this->string(50)->notNull(),
            'kode_variabel_marketplace'=> $this->string(3),
            'kode_variabel_marketplace_kategori'=> $this->string(150)->notNull(),
            'sku_produk' => $this->string(20)->notNull(),
        ]);

        $this->addPrimaryKey('setting_marketplace_kategori_pkey','setting_marketplace_kategori',array('kode_toko','kode_variabel_marketplace','kode_variabel_marketplace_kategori','sku_produk'));

        $this->addForeignKey('setting_marketplace_kategori_toko_fkey', 'setting_marketplace_kategori', 'kode_toko', 'toko', 'kode', 'RESTRICT', 'CASCADE');

        //sudah tidak berlaku karena ada kode_toko di reference tablenya
        //$this->addForeignKey('setting_marketplace_kategori_variabel_marketplace_fkey', 'setting_marketplace_kategori', 'kode_variabel_marketplace', 'variabel_marketplace', 'kode', 'RESTRICT', 'CASCADE');

        //sudah tidak berlaku karena ada kode_toko di reference tablenya
        //$this->addForeignKey('setting_marketplace_kategori_produk_fkey', 'setting_marketplace_kategori', 'sku_produk', 'produk', 'sku', 'RESTRICT', 'CASCADE');

        $this->batchInsert('setting_marketplace_kategori', ['kode_toko','kode_variabel_marketplace','kode_variabel_marketplace_kategori','sku_produk'],
        [
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0001'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0002'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0003'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0004'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0008'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0009'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0010'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0011'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0012'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0015'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0016'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0017'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0025'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0026'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0027'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0028'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0029'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0036'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0037'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0039'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0040'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0041'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0043'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0044'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0045'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0046'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0047'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0048'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0049'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0050'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0051'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0052'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0053'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0059'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0064'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0065'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0066'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0069'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0070'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0077'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0078'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0091'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0092'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0093'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0094'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0095'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0096'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0097'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0098'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0099'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0100'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0101'],
            ['hiiphooray-tani','bkl','pupuk-nutrisi-tanaman-8a1','SKUHT0102'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0005'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0006'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0007'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0013'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0014'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0018'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0019'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0020'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0021'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0022'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0023'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0024'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0034'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0035'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0038'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0054'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0055'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0056'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0060'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0061'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0062'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0063'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0067'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0068'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0071'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0072'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0073'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0074'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0075'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0076'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0079'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0080'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0083'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0084'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0085'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0086'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0087'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0088'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0089'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0090'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0103'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0104'],
            ['hiiphooray-tani','bkl','peralatan-berkebun-8a4','SKUHT0105'],
            ['hiiphooray-tani','bkl','benih-tanaman-898','SKUHT0030'],
            ['hiiphooray-tani','bkl','benih-tanaman-898','SKUHT0031'],
            ['hiiphooray-tani','bkl','benih-tanaman-898','SKUHT0032'],
            ['hiiphooray-tani','bkl','benih-tanaman-898','SKUHT0033'],
            ['hiiphooray-tani','bkl','benih-tanaman-898','SKUHT0042'],
            ['hiiphooray-tani','bkl','bibit-tanaman-89e','SKUHT0081'],
            ['hiiphooray-tani','bkl','bibit-tanaman-89e','SKUHT0082'],
            ['hiiphooray-tani','bkl','makanan-hewan-peliharaan-763','SKUHT0057'],
            ['hiiphooray-tani','bkl','makanan-hewan-peliharaan-763','SKUHT0058'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0001'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0002'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0003'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0004'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0005'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0006'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0007'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0008'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0009'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0010'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0011'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0012'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0013'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0014'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0015'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0016'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0017'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0018'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0019'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0020'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0021'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0022'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0023'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0024'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0025'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0026'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0027'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0028'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0029'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0030'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0031'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0032'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0033'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0034'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0035'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0036'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0037'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0038'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0039'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0040'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0041'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0042'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0043'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0044'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0045'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0046'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0047'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0048'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0049'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0050'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0051'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0052'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0053'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0054'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0055'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0056'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0057'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0058'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0059'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0060'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0061'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0062'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0063'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0064'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0065'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0066'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0067'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0068'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0069'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0070'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0071'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0072'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0073'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0074'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0075'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0076'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0077'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0078'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0079'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0080'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0081'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0082'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0083'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0084'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0085'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0086'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0087'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0088'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0089'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0090'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0091'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0092'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0093'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0094'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0095'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0096'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0097'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0098'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0099'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0100'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0101'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0102'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0103'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0104'],
            ['hiiphooray-tani','bli','Perlengkapan Taman Lainnya','SKUHT0105'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0001'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0002'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0003'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0004'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0005'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0006'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0007'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0008'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0009'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0010'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0011'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0012'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0013'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0014'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0015'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0016'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0017'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0018'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0019'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0020'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0021'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0022'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0023'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0024'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0025'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0026'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0027'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0028'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0029'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0030'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0031'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0032'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0033'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0034'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0035'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0036'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0037'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0038'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0039'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0040'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0041'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0042'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0043'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0044'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0045'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0046'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0047'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0048'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0049'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0050'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0051'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0052'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0053'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0054'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0055'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0056'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0057'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0058'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0059'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0060'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0061'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0062'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0063'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0064'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0065'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0066'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0067'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0068'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0069'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0070'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0071'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0072'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0073'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0074'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0075'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0076'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0077'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0078'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0079'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0080'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0081'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0082'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0083'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0084'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0085'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0086'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0087'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0088'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0089'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0090'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0091'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0092'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0093'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0094'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0095'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0096'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0097'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0098'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0099'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0100'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0101'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0102'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0103'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0104'],
            ['hiiphooray-tani','fbc','Home & Garden > Lawn & Garden > Gardening','SKUHT0105'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0001'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0002'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0003'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0004'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0005'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0006'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0007'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0008'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0009'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0010'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0011'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0012'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0013'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0014'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0015'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0016'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0017'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0018'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0019'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0020'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0021'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0022'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0023'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0024'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0025'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0026'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0027'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0028'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0029'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0030'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0031'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0032'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0033'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0034'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0035'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0036'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0037'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0038'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0039'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0040'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0041'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0042'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0043'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0044'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0045'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0046'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0047'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0048'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0049'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0050'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0051'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0052'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0053'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0054'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0055'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0056'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0057'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0058'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0059'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0060'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0061'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0062'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0063'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0064'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0065'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0066'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0067'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0068'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0069'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0070'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0071'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0072'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0073'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0074'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0075'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0076'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0077'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0078'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0079'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0080'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0081'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0082'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0083'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0084'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0085'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0086'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0087'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0088'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0089'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0090'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0091'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0092'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0093'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0094'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0095'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0096'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0097'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0098'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0099'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0100'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0101'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0102'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0103'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0104'],
            ['hiiphooray-tani','jdi','75061777 - Home Living / Outdoor & Garden / Lawn & Garden','SKUHT0105'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0001'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0002'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0003'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0004'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0005'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0006'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0007'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0008'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0009'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0010'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0011'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0012'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0013'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0014'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0015'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0016'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0017'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0018'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0019'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0020'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0021'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0022'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0023'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0024'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0025'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0026'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0027'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0028'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0029'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0030'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0031'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0032'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0033'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0034'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0035'],
            ['hiiphooray-tani','lzd','PembasmiRumputLiarHama','SKUHT0036'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0037'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0038'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0039'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0040'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0041'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0042'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0043'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0044'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0045'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0046'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0047'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0048'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0049'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0050'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0051'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0052'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0053'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0054'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0055'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0056'],
            ['hiiphooray-tani','lzd','MakananIkan','SKUHT0057'],
            ['hiiphooray-tani','lzd','MakananIkan','SKUHT0058'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0059'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0060'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0061'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0062'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0063'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0064'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0065'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0066'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0067'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0068'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0069'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0070'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0071'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0072'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0073'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0074'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0075'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0076'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0077'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0078'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0079'],
            ['hiiphooray-tani','lzd','PotPotBesarGuciTaman','SKUHT0080'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0081'],
            ['hiiphooray-tani','lzd','TanamanBijidanUmbi','SKUHT0082'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0083'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0084'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0085'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0086'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0087'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0088'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0089'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0090'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0091'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0092'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0093'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0094'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0095'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0096'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0097'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0098'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0099'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0100'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0101'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0102'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0103'],
            ['hiiphooray-tani','lzd','TanahPupukMulsa','SKUHT0104'],
            ['hiiphooray-tani','lzd','PeralatanKebun','SKUHT0105'],
            ['hiiphooray-tani','shp','9641','SKUHT0001'],
            ['hiiphooray-tani','shp','9641','SKUHT0002'],
            ['hiiphooray-tani','shp','9641','SKUHT0003'],
            ['hiiphooray-tani','shp','9641','SKUHT0004'],
            ['hiiphooray-tani','shp','12266','SKUHT0005'],
            ['hiiphooray-tani','shp','12266','SKUHT0006'],
            ['hiiphooray-tani','shp','12266','SKUHT0007'],
            ['hiiphooray-tani','shp','9641','SKUHT0008'],
            ['hiiphooray-tani','shp','9641','SKUHT0009'],
            ['hiiphooray-tani','shp','9641','SKUHT0010'],
            ['hiiphooray-tani','shp','9641','SKUHT0011'],
            ['hiiphooray-tani','shp','9641','SKUHT0012'],
            ['hiiphooray-tani','shp','12266','SKUHT0013'],
            ['hiiphooray-tani','shp','12266','SKUHT0014'],
            ['hiiphooray-tani','shp','9641','SKUHT0015'],
            ['hiiphooray-tani','shp','9641','SKUHT0016'],
            ['hiiphooray-tani','shp','9641','SKUHT0017'],
            ['hiiphooray-tani','shp','9639','SKUHT0018'],
            ['hiiphooray-tani','shp','9639','SKUHT0019'],
            ['hiiphooray-tani','shp','9639','SKUHT0020'],
            ['hiiphooray-tani','shp','9639','SKUHT0021'],
            ['hiiphooray-tani','shp','9639','SKUHT0022'],
            ['hiiphooray-tani','shp','9639','SKUHT0023'],
            ['hiiphooray-tani','shp','12266','SKUHT0024'],
            ['hiiphooray-tani','shp','9641','SKUHT0025'],
            ['hiiphooray-tani','shp','9641','SKUHT0026'],
            ['hiiphooray-tani','shp','9641','SKUHT0027'],
            ['hiiphooray-tani','shp','9641','SKUHT0028'],
            ['hiiphooray-tani','shp','9641','SKUHT0029'],
            ['hiiphooray-tani','shp','9640','SKUHT0030'],
            ['hiiphooray-tani','shp','9640','SKUHT0031'],
            ['hiiphooray-tani','shp','9640','SKUHT0032'],
            ['hiiphooray-tani','shp','9640','SKUHT0033'],
            ['hiiphooray-tani','shp','12266','SKUHT0034'],
            ['hiiphooray-tani','shp','12266','SKUHT0035'],
            ['hiiphooray-tani','shp','9641','SKUHT0036'],
            ['hiiphooray-tani','shp','9641','SKUHT0037'],
            ['hiiphooray-tani','shp','12266','SKUHT0038'],
            ['hiiphooray-tani','shp','9641','SKUHT0039'],
            ['hiiphooray-tani','shp','9641','SKUHT0040'],
            ['hiiphooray-tani','shp','9641','SKUHT0041'],
            ['hiiphooray-tani','shp','9640','SKUHT0042'],
            ['hiiphooray-tani','shp','9641','SKUHT0043'],
            ['hiiphooray-tani','shp','9641','SKUHT0044'],
            ['hiiphooray-tani','shp','9641','SKUHT0045'],
            ['hiiphooray-tani','shp','9641','SKUHT0046'],
            ['hiiphooray-tani','shp','9641','SKUHT0047'],
            ['hiiphooray-tani','shp','9641','SKUHT0048'],
            ['hiiphooray-tani','shp','9641','SKUHT0049'],
            ['hiiphooray-tani','shp','9641','SKUHT0050'],
            ['hiiphooray-tani','shp','9641','SKUHT0051'],
            ['hiiphooray-tani','shp','9641','SKUHT0052'],
            ['hiiphooray-tani','shp','9641','SKUHT0053'],
            ['hiiphooray-tani','shp','12266','SKUHT0054'],
            ['hiiphooray-tani','shp','12266','SKUHT0055'],
            ['hiiphooray-tani','shp','12266','SKUHT0056'],
            ['hiiphooray-tani','shp','2202','SKUHT0057'],
            ['hiiphooray-tani','shp','2202','SKUHT0058'],
            ['hiiphooray-tani','shp','9641','SKUHT0059'],
            ['hiiphooray-tani','shp','9639','SKUHT0060'],
            ['hiiphooray-tani','shp','9639','SKUHT0061'],
            ['hiiphooray-tani','shp','9639','SKUHT0062'],
            ['hiiphooray-tani','shp','9639','SKUHT0063'],
            ['hiiphooray-tani','shp','9641','SKUHT0064'],
            ['hiiphooray-tani','shp','12394','SKUHT0065'],
            ['hiiphooray-tani','shp','12394','SKUHT0066'],
            ['hiiphooray-tani','shp','12266','SKUHT0067'],
            ['hiiphooray-tani','shp','12266','SKUHT0068'],
            ['hiiphooray-tani','shp','9641','SKUHT0069'],
            ['hiiphooray-tani','shp','9641','SKUHT0070'],
            ['hiiphooray-tani','shp','12266','SKUHT0071'],
            ['hiiphooray-tani','shp','12266','SKUHT0072'],
            ['hiiphooray-tani','shp','9639','SKUHT0073'],
            ['hiiphooray-tani','shp','12266','SKUHT0074'],
            ['hiiphooray-tani','shp','12266','SKUHT0075'],
            ['hiiphooray-tani','shp','12266','SKUHT0076'],
            ['hiiphooray-tani','shp','9641','SKUHT0077'],
            ['hiiphooray-tani','shp','9641','SKUHT0078'],
            ['hiiphooray-tani','shp','9639','SKUHT0079'],
            ['hiiphooray-tani','shp','9639','SKUHT0080'],
            ['hiiphooray-tani','shp','9640','SKUHT0081'],
            ['hiiphooray-tani','shp','9640','SKUHT0082'],
            ['hiiphooray-tani','shp','12266','SKUHT0083'],
            ['hiiphooray-tani','shp','12266','SKUHT0084'],
            ['hiiphooray-tani','shp','12266','SKUHT0085'],
            ['hiiphooray-tani','shp','12266','SKUHT0086'],
            ['hiiphooray-tani','shp','12266','SKUHT0087'],
            ['hiiphooray-tani','shp','12266','SKUHT0088'],
            ['hiiphooray-tani','shp','12266','SKUHT0089'],
            ['hiiphooray-tani','shp','12266','SKUHT0090'],
            ['hiiphooray-tani','shp','9641','SKUHT0091'],
            ['hiiphooray-tani','shp','9641','SKUHT0092'],
            ['hiiphooray-tani','shp','9641','SKUHT0093'],
            ['hiiphooray-tani','shp','9641','SKUHT0094'],
            ['hiiphooray-tani','shp','9641','SKUHT0095'],
            ['hiiphooray-tani','shp','9641','SKUHT0096'],
            ['hiiphooray-tani','shp','9641','SKUHT0097'],
            ['hiiphooray-tani','shp','9641','SKUHT0098'],
            ['hiiphooray-tani','shp','12394','SKUHT0099'],
            ['hiiphooray-tani','shp','12394','SKUHT0100'],
            ['hiiphooray-tani','shp','12394','SKUHT0101'],
            ['hiiphooray-tani','shp','12394','SKUHT0102'],
            ['hiiphooray-tani','shp','12266','SKUHT0103'],
            ['hiiphooray-tani','shp','12266','SKUHT0104'],
            ['hiiphooray-tani','shp','12266','SKUHT0105'],
            ['hiiphooray-tani','tkp','1657','SKUHT0001'],
            ['hiiphooray-tani','tkp','1657','SKUHT0002'],
            ['hiiphooray-tani','tkp','1657','SKUHT0003'],
            ['hiiphooray-tani','tkp','1657','SKUHT0004'],
            ['hiiphooray-tani','tkp','3753','SKUHT0005'],
            ['hiiphooray-tani','tkp','3753','SKUHT0006'],
            ['hiiphooray-tani','tkp','3753','SKUHT0007'],
            ['hiiphooray-tani','tkp','1657','SKUHT0008'],
            ['hiiphooray-tani','tkp','1657','SKUHT0009'],
            ['hiiphooray-tani','tkp','1657','SKUHT0010'],
            ['hiiphooray-tani','tkp','1657','SKUHT0011'],
            ['hiiphooray-tani','tkp','1657','SKUHT0012'],
            ['hiiphooray-tani','tkp','1659','SKUHT0013'],
            ['hiiphooray-tani','tkp','1659','SKUHT0014'],
            ['hiiphooray-tani','tkp','1657','SKUHT0015'],
            ['hiiphooray-tani','tkp','1657','SKUHT0016'],
            ['hiiphooray-tani','tkp','1657','SKUHT0017'],
            ['hiiphooray-tani','tkp','1656','SKUHT0018'],
            ['hiiphooray-tani','tkp','1656','SKUHT0019'],
            ['hiiphooray-tani','tkp','1656','SKUHT0020'],
            ['hiiphooray-tani','tkp','1656','SKUHT0021'],
            ['hiiphooray-tani','tkp','1656','SKUHT0022'],
            ['hiiphooray-tani','tkp','1656','SKUHT0023'],
            ['hiiphooray-tani','tkp','4235','SKUHT0024'],
            ['hiiphooray-tani','tkp','1657','SKUHT0025'],
            ['hiiphooray-tani','tkp','1657','SKUHT0026'],
            ['hiiphooray-tani','tkp','1657','SKUHT0027'],
            ['hiiphooray-tani','tkp','1657','SKUHT0028'],
            ['hiiphooray-tani','tkp','1657','SKUHT0029'],
            ['hiiphooray-tani','tkp','1655','SKUHT0030'],
            ['hiiphooray-tani','tkp','1655','SKUHT0031'],
            ['hiiphooray-tani','tkp','1655','SKUHT0032'],
            ['hiiphooray-tani','tkp','1655','SKUHT0033'],
            ['hiiphooray-tani','tkp','3750','SKUHT0034'],
            ['hiiphooray-tani','tkp','3750','SKUHT0035'],
            ['hiiphooray-tani','tkp','1657','SKUHT0036'],
            ['hiiphooray-tani','tkp','1657','SKUHT0037'],
            ['hiiphooray-tani','tkp','4235','SKUHT0038'],
            ['hiiphooray-tani','tkp','1657','SKUHT0039'],
            ['hiiphooray-tani','tkp','1657','SKUHT0040'],
            ['hiiphooray-tani','tkp','1657','SKUHT0041'],
            ['hiiphooray-tani','tkp','1655','SKUHT0042'],
            ['hiiphooray-tani','tkp','1657','SKUHT0043'],
            ['hiiphooray-tani','tkp','1657','SKUHT0044'],
            ['hiiphooray-tani','tkp','1657','SKUHT0045'],
            ['hiiphooray-tani','tkp','1657','SKUHT0046'],
            ['hiiphooray-tani','tkp','1657','SKUHT0047'],
            ['hiiphooray-tani','tkp','1657','SKUHT0048'],
            ['hiiphooray-tani','tkp','1657','SKUHT0049'],
            ['hiiphooray-tani','tkp','1657','SKUHT0050'],
            ['hiiphooray-tani','tkp','1657','SKUHT0051'],
            ['hiiphooray-tani','tkp','1657','SKUHT0052'],
            ['hiiphooray-tani','tkp','1657','SKUHT0053'],
            ['hiiphooray-tani','tkp','1659','SKUHT0054'],
            ['hiiphooray-tani','tkp','1659','SKUHT0055'],
            ['hiiphooray-tani','tkp','1659','SKUHT0056'],
            ['hiiphooray-tani','tkp','4130','SKUHT0057'],
            ['hiiphooray-tani','tkp','4130','SKUHT0058'],
            ['hiiphooray-tani','tkp','1657','SKUHT0059'],
            ['hiiphooray-tani','tkp','1656','SKUHT0060'],
            ['hiiphooray-tani','tkp','1656','SKUHT0061'],
            ['hiiphooray-tani','tkp','1656','SKUHT0062'],
            ['hiiphooray-tani','tkp','1656','SKUHT0063'],
            ['hiiphooray-tani','tkp','1657','SKUHT0064'],
            ['hiiphooray-tani','tkp','1753','SKUHT0065'],
            ['hiiphooray-tani','tkp','1753','SKUHT0066'],
            ['hiiphooray-tani','tkp','4133','SKUHT0067'],
            ['hiiphooray-tani','tkp','4133','SKUHT0068'],
            ['hiiphooray-tani','tkp','1657','SKUHT0069'],
            ['hiiphooray-tani','tkp','1657','SKUHT0070'],
            ['hiiphooray-tani','tkp','4235','SKUHT0071'],
            ['hiiphooray-tani','tkp','1656','SKUHT0072'],
            ['hiiphooray-tani','tkp','1656','SKUHT0073'],
            ['hiiphooray-tani','tkp','1659','SKUHT0074'],
            ['hiiphooray-tani','tkp','1659','SKUHT0075'],
            ['hiiphooray-tani','tkp','1659','SKUHT0076'],
            ['hiiphooray-tani','tkp','1657','SKUHT0077'],
            ['hiiphooray-tani','tkp','1657','SKUHT0078'],
            ['hiiphooray-tani','tkp','1656','SKUHT0079'],
            ['hiiphooray-tani','tkp','1656','SKUHT0080'],
            ['hiiphooray-tani','tkp','1655','SKUHT0081'],
            ['hiiphooray-tani','tkp','1655','SKUHT0082'],
            ['hiiphooray-tani','tkp','1659','SKUHT0083'],
            ['hiiphooray-tani','tkp','1659','SKUHT0084'],
            ['hiiphooray-tani','tkp','577','SKUHT0085'],
            ['hiiphooray-tani','tkp','4240','SKUHT0086'],
            ['hiiphooray-tani','tkp','1659','SKUHT0087'],
            ['hiiphooray-tani','tkp','4284','SKUHT0088'],
            ['hiiphooray-tani','tkp','4284','SKUHT0089'],
            ['hiiphooray-tani','tkp','1659','SKUHT0090'],
            ['hiiphooray-tani','tkp','1657','SKUHT0091'],
            ['hiiphooray-tani','tkp','1657','SKUHT0092'],
            ['hiiphooray-tani','tkp','1657','SKUHT0093'],
            ['hiiphooray-tani','tkp','1657','SKUHT0094'],
            ['hiiphooray-tani','tkp','1657','SKUHT0095'],
            ['hiiphooray-tani','tkp','1657','SKUHT0096'],
            ['hiiphooray-tani','tkp','1657','SKUHT0097'],
            ['hiiphooray-tani','tkp','1657','SKUHT0098'],
            ['hiiphooray-tani','tkp','1753','SKUHT0099'],
            ['hiiphooray-tani','tkp','1753','SKUHT0100'],
            ['hiiphooray-tani','tkp','1753','SKUHT0101'],
            ['hiiphooray-tani','tkp','1753','SKUHT0102'],
            ['hiiphooray-tani','tkp','1659','SKUHT0103'],
            ['hiiphooray-tani','tkp','1659','SKUHT0104'],
            ['hiiphooray-tani','tkp','577','SKUHT0105'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0001'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0002'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0003'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0004'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0005'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0006'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0007'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0008'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0009'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0010'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0011'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0012'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0013'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0014'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0015'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0016'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0017'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0018'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0019'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0020'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0021'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0022'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0023'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0024'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0025'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0026'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0027'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0028'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0029'],
            ['hiiphooray-tani','zbz','Benih','SKUHT0030'],
            ['hiiphooray-tani','zbz','Benih','SKUHT0031'],
            ['hiiphooray-tani','zbz','Benih','SKUHT0032'],
            ['hiiphooray-tani','zbz','Benih','SKUHT0033'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0034'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0035'],
            ['hiiphooray-tani','zbz','Pestisida','SKUHT0036'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0037'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0038'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0039'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0040'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0041'],
            ['hiiphooray-tani','zbz','Benih','SKUHT0042'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0043'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0044'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0045'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0046'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0047'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0048'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0049'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0050'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0051'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0052'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0053'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0054'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0055'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0056'],
            ['hiiphooray-tani','zbz','Perikanan','SKUHT0057'],
            ['hiiphooray-tani','zbz','Perikanan','SKUHT0058'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0059'],
            ['hiiphooray-tani','zbz','Planter Bag','SKUHT0060'],
            ['hiiphooray-tani','zbz','Planter Bag','SKUHT0061'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0062'],
            ['hiiphooray-tani','zbz','Polybag Seedling Bag','SKUHT0063'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0064'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0065'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0066'],
            ['hiiphooray-tani','zbz','Perikanan','SKUHT0067'],
            ['hiiphooray-tani','zbz','Perikanan','SKUHT0068'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0069'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0070'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0071'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0072'],
            ['hiiphooray-tani','zbz','Planter Bag','SKUHT0073'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0074'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0075'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0076'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0077'],
            ['hiiphooray-tani','zbz','Pupuk','SKUHT0078'],
            ['hiiphooray-tani','zbz','Drum','SKUHT0079'],
            ['hiiphooray-tani','zbz','Drum','SKUHT0080'],
            ['hiiphooray-tani','zbz','Bibit Tanaman','SKUHT0081'],
            ['hiiphooray-tani','zbz','Bibit Tanaman','SKUHT0082'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0083'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0084'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0085'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0086'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0087'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0088'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0089'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0090'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0091'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0092'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0093'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0094'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0095'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0096'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0097'],
            ['hiiphooray-tani','zbz','ZPT dan Hormon','SKUHT0098'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0099'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0100'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0101'],
            ['hiiphooray-tani','zbz','Media Tanam','SKUHT0102'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0103'],
            ['hiiphooray-tani','zbz','Perlengkapan Tani','SKUHT0104'],
            ['hiiphooray-tani','zbz','Peralatan Tani','SKUHT0105'],
        ]);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('setting_marketplace_kategori');
    }
}
